name: Main Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: shsingh08/GitHub-actions-runner-ss/.github/workflows/reusable-deploy.yml@main
    with:
      environment: "prod"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
